# Generated by Django 5.0.1 on 2024-01-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
